#!/usr/bin/env python3
# move tanacross files to new folder
# using json file generated by detector
import os, shutil, json

indir = "clips/"
outdir = "tnc/"

# create the output directory if it doesn't exist
if not os.path.exists(outdir):
    os.makedirs(outdir)


with open('detect.json', 'r') as f:
  files = json.load(f)

tncfiles = {k:v for (k,v) in files.items() if  v['language'] == 'tnc'}

for fn in tncfiles.keys():
	shutil.copy(os.path.join(indir,fn), outdir)